FROM node:15

LABEL author="Vetal-V"


RUN git clone https://github.com/Vetal-V/Coursework-DS.git
WORKDIR Coursework-DS/frontend/callboard-front/
RUN npm install

EXPOSE 8080
CMD [ "npm", "run", "serve" ]