FROM python:3.8.6-alpine

LABEL author="Vetal-V"

ENV PROJECT_ROOT /app
WORKDIR $PROJECT_ROOT

RUN apk update && apk add gcc libc-dev make git libffi-dev openssl-dev python3-dev libxml2-dev libxslt-dev 
RUN git clone https://github.com/Vetal-V/Coursework-DS.git
WORKDIR Coursework-DS

RUN ls -la
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')"
RUN python manage.py loaddata ./import_data/filters.json
RUN python manage.py loaddata ./import_data/categories.json
RUN python manage.py loaddata ./import_data/terms.json

CMD python manage.py runserver 0.0.0.0:8000