apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 30000
      protocol: TCP