---
- name: create deploy directory
  become: yes
  become_user: ubuntu
  file:
    path: /home/ubuntu/.kube/deploy
    state: directory
    mode: 0755

- name: copy kubernetes files
  template:
    src: "{{ item }}"
    dest: "/home/ubuntu/.kube/deploy/"
    owner: ubuntu 
    group: ubuntu 
    mode: 0777
  with_items:
    - "django-deployment.yml"
    - "django-service.yml"
    - "frontend-deployment.yml"
    - "frontend-service.yml"