---
- name: copy kubernetes files
  template:
    src: "{{ item }}"
    dest: "/home/ubuntu/.kube/"
    owner: root 
    group: root 
    mode: 0777
  with_items:
    - "django-deployment.yml"
    - "django-service.yml"

- name: set folder kubect
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: 0777

- name: copy base conf to user folder
  command: cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  become: true

- name: change permission to config
  command: chmod 777 /home/ubuntu/.kube/config
  args:
    warn: false

- name: apply from yml files
  command: "kubectl apply -f ."
  become: true
  args:
    chdir: /home/ubuntu/.kube/
    